### ISSUE TITLE
add support for Tessa

### ISSUE THREAD

**Issue by abenjak** [felicianotech/zoom-mgr#23]
Thanks for the very convenient tool!

Could you please add Tessa to the list of supported OS?
It works on my Linux Mint 19.1.

Cheers,
Andrej

**Comment by felicianotech** [comment]
Thank you!

I added support for versions of Linux Mint v19 and up. I tested using Cinnamon. This should be supported starting at zoom-mgr v0.9.0 and up.

**Comment by felicianotech** [comment]
@abenjak Did this work out for you?

**Comment by abenjak** [comment]
Yes, thank you!
    Good solution to look for UBUNTU_CODENAME instead of
    VERSION_CODENAME :)
    
    Cheers,
    Andrej
    
    On 15/01/2021 19:00, Ricardo N
      Feliciano wrote:
    
    
      
      @abenjak
        Did this work out for you?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/felicianotech/zoom-mgr/issues/23#issuecomment-761093287",
"url": "https://github.com/felicianotech/zoom-mgr/issues/23#issuecomment-761093287",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
