### ISSUE TITLE
Need to download an old version of zoom:  version 4.6.9

### ISSUE THREAD

**Issue by saullubkin** [felicianotech/zoom-mgr#28]
Hi Feliciano!

I've been happily using zoom-mgr to keep up with the latest version of zoom.

But, today I was running a zoom lecture, recording it -- and lost power.   A .zoom file was left (not an .mp4).  I tried the methods suggested by the official zoom site -- they didn't work.

The last version of zoom that let you convert a .zoom file by double clicking on it was 4.6.9.  So I'd like to download this old version of zoom.

I thought that hopefully you can help me with this.

Thanks in advance,

  --  Saul

**Comment by felicianotech** [comment]
Hi.

Currently I don't believe this is possible. This CLI doesn't support it but also, I don't believe Zoom keeps old `.deb` files around on their website. Without them, I couldn't implement this feature.

I'll keep this Issue opened for a little longer while I do some research but I'm thinking I won't be able to do this.

**Comment by saullubkin** [comment]
OK.

Thanks,

  --  Saul
________________________________
From: Ricardo N Feliciano ***@***.***>
Sent: Thursday, May 20, 2021 7:26 PM
To: felicianotech/zoom-mgr ***@***.***>
Cc: Lubkin, Saul ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [felicianotech/zoom-mgr] Need to download an old version of zoom: version 4.6.9 (#28)


Hi.

Currently I don't believe this is possible. This CLI doesn't support it but also, I don't believe Zoom keeps old .deb files around on their website. Without them, I couldn't implement this feature.

I'll keep this Issue opened for a little longer while I do some research but I'm thinking I won't be able to do this.

**Comment by saullubkin** [comment]
Hi Ricardo!

There is a very minor syntax error in the latest version of zoom-mgr.sh.

Namely, the next to last line; line 102 causes an error message; the line is just

;;

Putting a # in front of the line removes the bash error message.

  --  Saul

**Comment by FelicianoTech** [comment]
Sorry but I am deprecating this project. Please see the note on the readme.
