### ISSUE TITLE
zoom-mgr.sh now doesn't upgrade itself

### ISSUE THREAD

**Issue by saullubkin** [felicianotech/zoom-mgr#37]
Hi Ricardo!

zoom-mgr.sh update 
now is correctly updating zoom, when an update is needed, and correctly doesn't update zoom when the newest version is already there.

But still one very minor problem:  zoom-mgr.sh update doesn't appear to be updating zoom-mgr.sh itself:  running zoom-mgr.sh update, we are told that version v0.10.0 is available; but after running the script, the zoom-mgr.sh is version 0.9.1.
  --  Saul

**Comment by felicianotech** [comment]
I can confirm this problem. Thank you for reporting. I'll get it fixed soon.

**Comment by saullubkin** [comment]
Thanks.

  --  Saul
________________________________
From: Ricardo N Feliciano ***@***.***>
Sent: Wednesday, May 26, 2021 2:05 PM
To: felicianotech/zoom-mgr ***@***.***>
Cc: Lubkin, Saul ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [felicianotech/zoom-mgr] zoom-mgr.sh now doesn't upgrade itself (#37)


I can confirm this problem. Thank you for reporting. I'll get it fixed soon.

**Comment by FelicianoTech** [comment]
Hi @saullubkin. This should be fixed now. When you run an update, it should update to v0.10.1. Once you get that update, it also will only update Zoom when there's an actual update.

**Comment by saullubkin** [comment]
Works perfectly now!
Thanks!

  -- Saul
