### ISSUE TITLE
Does not work properly

### ISSUE THREAD

**Issue by tomgs** [felicianotech/zoom-mgr#5]
Update just removes and does not re-install, and so does install it seems.

Haven't taken a look at the script closely, will do so a bit later, but it might be a flag thing.

**Comment by moorepants** [comment]
I used the script several days ago and it seemed to work, but when I tried today I'm getting the same issues as @tomgs. It installs and then removes zoom.

**Comment by felicianotech** [comment]
I'm seeing that too. Something broke. I'll check into this today. Thanks for reporting @tomgs.

**Comment by felicianotech** [comment]
This has been fixed, thanks again.

You need to update Zoom MGR itself in order to have it working again. Updating it is the same as installing it. In the directory where you already downloaded it:

```bash
curl -O https://raw.githubusercontent.com/felicianotech/zoom-mgr/master/zoom-mgr.sh
```

**Comment by tomgs** [comment]
Can confirm is working now. Thanks!
